export const majorOptions = [
  "Undeclared",
  "Actuarial Science",
  "Accounting",
  "Architecture",
  "Biology",
  "Business Administration",
  "Chemistry",
  "Cloud Computing",
  "Computer Science",
  "Construction Management",
  "Economics",
  "Electrical Engineering",
  "Entrepreneurship",
  "Finance",
  "Hospitality Management",
  "Human Resource Management",
  "Information Science",
  "Information Systems",
  "Interior Design",
  "Marketing",
  "Mathematics",
  "Nursing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Civil Engineering",
  "English",
  "History",
  "Sociology",
];
